name: test-action

on: push

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Test CFBundleShortVersionString
      - id: CFResult
      - uses: 2CodersStudio/ActionPlistVersion@main
        with:
          plist-path: test/Info-CFBundleShortVersionString.plist
          key: CFBundleShortVersionString
      - name: Test XCFrameworkFormatVersion
      - id: XCResult
      - uses: 2CodersStudio/ActionPlistVersion@main
        with:
          plist-path: test/Info-XCFrameworkFormatVersion.plist
          key: XCFrameworkFormatVersion
      - name: evaluate results CFResult
      - run: |
        if [[ ${{ steps.XCResult.outputs.version }} == "CFBundleShortVersionString" ]];
          then echo "CFResult OK"
        else
          echo "CFResult NOK"
          exit 1
        fi
        if [[ ${{ steps.XCResult.outputs.version }} == "XCFrameworkFormatVersion" ]];
          then echo "XCResult OK"
        else
          echo "XCResult NOK"
          exit 1
        fi
        

