name: test-action

on: push

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2.3.1
      - uses: 2CodersStudio/ActionPlistVersion@main
        with:
          plist-path: test/Info-CFBundleShortVersionString.plist
          key: CFBundleShortVersionString
      - uses: 2CodersStudio/ActionPlistVersion@main
        with:
          plist-path: test/Info-XCFrameworkFormatVersion.plist
          key: XCFrameworkFormatVersion