name: test-action

on: 
  push:
    branches: 
      - main
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.1
        name: Test CFBundleShortVersionString
      - uses: 2CodersStudio/ActionPlistVersion@main
        id: CFResult
        with:
          plist-path: test/Info-CFBundleShortVersionString.plist
          key: CFBundleShortVersionString
      - uses: 2CodersStudio/ActionPlistVersion@main
        name: Test XCFrameworkFormatVersion
        id: XCResult
        with:
            plist-path: test/Info-XCFrameworkFormatVersion.plist
            key: XCFrameworkFormatVersion
      - name: Test XCResult
        run: |
           if [[ ${{ steps.XCResult.outputs.version != "1.0" }} ]];
             then echo "XCResult NOK"
           fi
      - name: Test CFResult
        run: |
           if [[ ${{ steps.CFResult.outputs.version != "1.0.3" }} ]];
             then echo "CFResult NOK"
           fi


