name: test-action

on: 
  push:
    branches: 
      - main
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Test CFBundleShortVersionString
      - id: CFResult
      - uses: 2CodersStudio/ActionPlistVersion@main
        with:
          plist-path: test/Info-CFBundleShortVersionString.plist
          key: CFBundleShortVersionString
      - name: Test CFResult
        run: |
          if [[ ${{ steps.CFResult.outputs.version != "1.0.3" }} ]];
            then echo "CFResult NOK"
          fi  
      - name: Test XCFrameworkFormatVersion
        id: XCResult
        uses: 2CodersStudio/ActionPlistVersion@main
        with:
            plist-path: test/Info-XCFrameworkFormatVersion.plist
            key: XCFrameworkFormatVersion
      - name: Test XCResult
        run: |
          if [[ ${{ steps.XCResult.outputs.version != "1.0" }} ]];
            then echo "XCResult NOK"
          fi

